# permissions for end users to edit brokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: meshery-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: broker-editor-role
rules:
- apiGroups:
  - meshery.meshery.layer5.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meshery.meshery.layer5.io
  resources:
  - brokers/status
  verbs:
  - get
