---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - meshery.meshery.layer5.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meshery.meshery.layer5.io
  resources:
  - brokers/finalizers
  verbs:
  - update
- apiGroups:
  - meshery.meshery.layer5.io
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
